"""Persisted observations generated by future KhataFlow AI agents."""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import Field

from app.models.base import MongoDocument, MongoId, SchemaModel, utc_now
from app.models.enums import InsightCategory, InsightSeverity


class InsightEvidence(SchemaModel):
    source_collection: str = Field(min_length=1, max_length=80, alias="sourceCollection")
    source_id: MongoId | None = Field(default=None, alias="sourceId")
    description: str = Field(min_length=1, max_length=1000)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AIInsight(MongoDocument):
    business_id: UUID = Field(alias="businessId")
    category: InsightCategory
    severity: InsightSeverity = InsightSeverity.INFO
    title: str = Field(min_length=1, max_length=180)
    summary: str = Field(min_length=1, max_length=4000)
    evidence: list[InsightEvidence] = Field(default_factory=list)
    related_entity_ids: list[MongoId] = Field(default_factory=list, alias="relatedEntityIds")
    confidence: float | None = Field(default=None, ge=0, le=1)
    suggested_action: str | None = Field(default=None, max_length=2000, alias="suggestedAction")
    agent_name: str | None = Field(default=None, max_length=100, alias="agentName")
    generated_at: datetime = Field(default_factory=utc_now, alias="generatedAt")
    resolution_metadata: dict[str, Any] = Field(default_factory=dict, alias="resolutionMetadata")
